# Generated by Django 4.0.3 on 2023-11-03 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imeArtikla', models.CharField(max_length=50)),
                ('cijenaArtikla', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Artikli',
            },
        ),
        migrations.CreateModel(
            name='SpecijalizacijaRačunovođe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipSpecijalizacije', models.IntegerField(choices=[(0, 'Računi'), (1, 'Ponude'), (2, 'InterniDokumenti')])),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specijalizacije', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Specijalizacije Računovođe',
            },
        ),
        migrations.CreateModel(
            name='Račun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekstDokumenta', models.TextField()),
                ('linkSlike', models.CharField(max_length=400)),
                ('vrijemeSkeniranja', models.DateTimeField()),
                ('imeKlijenta', models.CharField(max_length=30)),
                ('ukupnaCijena', models.IntegerField()),
                ('artikli', models.ManyToManyField(to='dokumenti.artikl')),
                ('potpisaoDirektor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potpisao_dokument', to=settings.AUTH_USER_MODEL)),
                ('potvrdioRevizor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potvrdio_dokument', to=settings.AUTH_USER_MODEL)),
                ('pregledaoRačunovođa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_pregledao_dokument', to=settings.AUTH_USER_MODEL)),
                ('skeniraoKorisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_skenirao_dokument', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Računi',
            },
        ),
        migrations.CreateModel(
            name='Ponuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekstDokumenta', models.TextField()),
                ('linkSlike', models.CharField(max_length=400)),
                ('vrijemeSkeniranja', models.DateTimeField()),
                ('ukupnaCijena', models.IntegerField()),
                ('artikli', models.ManyToManyField(to='dokumenti.artikl')),
                ('potpisaoDirektor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potpisao_dokument', to=settings.AUTH_USER_MODEL)),
                ('potvrdioRevizor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potvrdio_dokument', to=settings.AUTH_USER_MODEL)),
                ('pregledaoRačunovođa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_pregledao_dokument', to=settings.AUTH_USER_MODEL)),
                ('skeniraoKorisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_skenirao_dokument', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ponude',
            },
        ),
        migrations.CreateModel(
            name='InterniDokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekstDokumenta', models.TextField()),
                ('linkSlike', models.CharField(max_length=400)),
                ('vrijemeSkeniranja', models.DateTimeField()),
                ('potpisaoDirektor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potpisao_dokument', to=settings.AUTH_USER_MODEL)),
                ('potvrdioRevizor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potvrdio_dokument', to=settings.AUTH_USER_MODEL)),
                ('pregledaoRačunovođa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_pregledao_dokument', to=settings.AUTH_USER_MODEL)),
                ('skeniraoKorisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_skenirao_dokument', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interni Dokumenti',
            },
        ),
    ]
