# Generated by Django 4.2.6 on 2023-12-30 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dokumenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arhiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekstDokumenta', models.TextField()),
                ('linkSlike', models.CharField(max_length=400)),
                ('vrijemeSkeniranja', models.DateTimeField()),
                ('dokumentId', models.IntegerField()),
                ('vrijemeArhiviranja', models.DateTimeField()),
                ('potvrdioRevizor', models.BooleanField(default=False)),
                ('potpisaoDirektor', models.BooleanField(default=False)),
                ('pregledaoRačunovođa', models.BooleanField(default=False)),
                ('direktor', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Direktori'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potpisao_dokument', to=settings.AUTH_USER_MODEL)),
                ('korisnik', models.ForeignKey(limit_choices_to={'groups__name': 'Zaposlenici'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_skenirao_dokument', to=settings.AUTH_USER_MODEL)),
                ('računovođa', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Računovođe'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_pregledao_dokument', to=settings.AUTH_USER_MODEL)),
                ('revizor', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Revizori'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potvrdio_dokument', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Arhive',
            },
        ),
        migrations.CreateModel(
            name='InterniDokumentArhiviran',
            fields=[
                ('arhiva_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dokumenti.arhiva')),
            ],
            options={
                'verbose_name_plural': 'Arhivirani interni dokumenti',
            },
            bases=('dokumenti.arhiva',),
        ),
        migrations.CreateModel(
            name='NedefiniraniDokumentArhiviran',
            fields=[
                ('arhiva_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dokumenti.arhiva')),
            ],
            options={
                'verbose_name_plural': 'Arhivirani nedefinirani dokumenti',
            },
            bases=('dokumenti.arhiva',),
        ),
        migrations.CreateModel(
            name='RačunArhiviran',
            fields=[
                ('arhiva_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dokumenti.arhiva')),
                ('imeKlijenta', models.CharField(max_length=30)),
                ('ukupnaCijena', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('artikli', models.ManyToManyField(to='dokumenti.artikl')),
            ],
            options={
                'verbose_name_plural': 'Arhivirani računi',
            },
            bases=('dokumenti.arhiva',),
        ),
        migrations.CreateModel(
            name='PonudaArhivirana',
            fields=[
                ('arhiva_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dokumenti.arhiva')),
                ('ukupnaCijena', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('artikli', models.ManyToManyField(to='dokumenti.artikl')),
            ],
            options={
                'verbose_name_plural': 'Arhivirane ponude',
            },
            bases=('dokumenti.arhiva',),
        ),
    ]
