# Generated by Django 4.0.3 on 2023-11-03 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dokumenti', '0002_alter_internidokument_potpisaodirektor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specijalizacijaračunovođe',
            name='korisnik',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Računovođe'}, on_delete=django.db.models.deletion.CASCADE, related_name='specijalizacije', to=settings.AUTH_USER_MODEL),
        ),
    ]
