# Generated by Django 4.2.6 on 2024-01-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenti', '0002_arhiva_internidokumentarhiviran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arhiva',
            name='pregledaoRačunovođa',
        ),
    ]
