# Generated by Django 4.2.6 on 2024-01-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenti', '0003_remove_arhiva_pregledaoračunovođa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='oznakaDokumenta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
