# Generated by Django 4.0.3 on 2023-11-03 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dokumenti', '0004_alter_artikl_cijenaartikla_alter_ponuda_ukupnacijena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponuda',
            name='ukupnaCijena',
        ),
        migrations.AlterField(
            model_name='internidokument',
            name='potpisaoDirektor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Direktori'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potpisao_dokument', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internidokument',
            name='pregledaoRačunovođa',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Računovođe'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_pregledao_dokument', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ponuda',
            name='potpisaoDirektor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Direktori'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potpisao_dokument', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ponuda',
            name='pregledaoRačunovođa',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Računovođe'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_pregledao_dokument', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='račun',
            name='potpisaoDirektor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Direktori'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potpisao_dokument', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='račun',
            name='pregledaoRačunovođa',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Računovođe'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_pregledao_dokument', to=settings.AUTH_USER_MODEL),
        ),
    ]
