# Generated by Django 4.0.3 on 2023-11-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenti', '0005_remove_ponuda_ukupnacijena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='račun',
            name='ukupnaCijena',
        ),
    ]
