# Generated by Django 4.2.6 on 2023-11-09 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dokumenti', '0006_remove_račun_ukupnacijena'),
    ]

    operations = [
        migrations.AddField(
            model_name='internidokument',
            name='potpisan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internidokument',
            name='potvrđen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internidokument',
            name='pregledan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ponuda',
            name='potpisan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ponuda',
            name='potvrđen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ponuda',
            name='pregledan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='račun',
            name='potpisan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='račun',
            name='potvrđen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='račun',
            name='pregledan',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NedefiniraniDokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekstDokumenta', models.TextField()),
                ('linkSlike', models.CharField(max_length=400)),
                ('vrijemeSkeniranja', models.DateTimeField()),
                ('pregledan', models.BooleanField(default=False)),
                ('potvrđen', models.BooleanField(default=False)),
                ('potpisan', models.BooleanField(default=False)),
                ('potpisaoDirektor', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Direktori'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potpisao_dokument', to=settings.AUTH_USER_MODEL)),
                ('potvrdioRevizor', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Revizori'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_potvrdio_dokument', to=settings.AUTH_USER_MODEL)),
                ('pregledaoRačunovođa', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Računovođe'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_pregledao_dokument', to=settings.AUTH_USER_MODEL)),
                ('skeniraoKorisnik', models.ForeignKey(limit_choices_to={'groups__name': 'Zaposlenici'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_skenirao_dokument', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Nedefinirani Dokumenti',
            },
        ),
    ]
