# Generated by Django 4.2.6 on 2023-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenti', '0009_ponuda_ukupnacijena_račun_ukupnacijena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internidokument',
            name='točnoSkeniran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nedefiniranidokument',
            name='točnoSkeniran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ponuda',
            name='točnoSkeniran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='račun',
            name='točnoSkeniran',
            field=models.BooleanField(default=False),
        ),
    ]
