# Generated by Django 4.2.6 on 2023-11-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenti', '0010_internidokument_točnoskeniran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internidokument',
            name='točnoSkeniran',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nedefiniranidokument',
            name='točnoSkeniran',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponuda',
            name='točnoSkeniran',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='račun',
            name='točnoSkeniran',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
