# Generated by Django 4.2.6 on 2023-12-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenti', '0011_alter_internidokument_točnoskeniran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internidokument',
            name='pregledaoRačunovođa',
        ),
        migrations.RemoveField(
            model_name='nedefiniranidokument',
            name='pregledaoRačunovođa',
        ),
        migrations.RemoveField(
            model_name='ponuda',
            name='pregledaoRačunovođa',
        ),
        migrations.RemoveField(
            model_name='račun',
            name='pregledaoRačunovođa',
        ),
    ]
