# Generated by Django 4.2.6 on 2023-12-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenti', '0012_remove_internidokument_pregledaoračunovođa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internidokumentarhiviran',
            name='pregledaoRačunovođa',
        ),
        migrations.RemoveField(
            model_name='nedefiniranidokumentarhiviran',
            name='pregledaoRačunovođa',
        ),
        migrations.RemoveField(
            model_name='ponudaarhivirana',
            name='pregledaoRačunovođa',
        ),
        migrations.RemoveField(
            model_name='računarhiviran',
            name='pregledaoRačunovođa',
        ),
    ]
